version: '3.8'
services:
  web:
    image: parkjungyu26/my-node-app:latest
    ports:
      - '8080:3000' # 호스트 포트 8080을 컨테이너 포트 3000으로 매핑
    restart: always
    environment:
      PORT: 3000 # 명확히 PORT를 하드코딩 (환경 변수 전달 문제 해결을 위해)
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000 || exit 1'] # 컨테이너 내부의 포트 번호도 3000으로 명확히 사용
      interval: 1m30s # 서버가 완전히 시작될 시간을 제공하기 위해 90초로 설정
      timeout: 10s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - ./logs:/usr/src/app/logs # 호스트의 logs 폴더를 컨테이너와 공유
